# Generated by Django 4.1.4 on 2022-12-29 15:52

from django.db import migrations, models
import short_url_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("short_url_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortener",
            name="short_url",
            field=models.CharField(
                blank=True,
                default=short_url_app.models.create_random_code,
                max_length=15,
                unique=True,
                validators=[short_url_app.models.validate_short_url],
            ),
        ),
    ]
