# Generated by Django 4.1.4 on 2023-01-03 20:38

from django.db import migrations, models
import url_shortener.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shortener",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("times_followed", models.PositiveIntegerField(default=0)),
                (
                    "url",
                    models.URLField(validators=[url_shortener.models.validate_url]),
                ),
                (
                    "short_url",
                    models.CharField(
                        blank=True,
                        default=url_shortener.models.create_random_code,
                        max_length=7,
                        unique=True,
                        validators=[url_shortener.models.validate_short_url],
                    ),
                ),
            ],
        ),
    ]
